ALTER TABLE graphs
  ALTER COLUMN measures DROP NOT NULL,
  ALTER COLUMN dimensions DROP NOT NULL,
  ALTER COLUMN dates DROP NOT NULL,
  ALTER COLUMN filters DROP NOT NULL,
  ALTER COLUMN order_by_field DROP NOT NULL,
  ALTER COLUMN order_by_field DROP DEFAULT,
  ALTER COLUMN order_by_direction DROP NOT NULL,
  ALTER COLUMN order_by_direction DROP DEFAULT,
  ALTER COLUMN legend_position DROP NOT NULL,
  ALTER COLUMN legend_position DROP DEFAULT,
  ALTER COLUMN kpi_show_trend DROP NOT NULL,
  ALTER COLUMN max_data_points DROP NOT NULL,
  ALTER COLUMN max_data_points DROP DEFAULT,
  ALTER COLUMN primary_dimension DROP NOT NULL,
  ALTER COLUMN primary_dimension DROP DEFAULT,
  ALTER COLUMN selected_measure DROP NOT NULL,
  ALTER COLUMN selected_measure DROP DEFAULT;
