import {
    GraphQLObjectType,
    GraphQLString,
    GraphQLID,
    GraphQLList,
    GraphQLInt,
    GraphQLBoolean,
    GraphQLFloat,
    GraphQLInputObjectType,
    GraphQLNonNull,
} from 'graphql';
import { GraphQLJSON } from 'graphql-scalars';
import {
    ChartTypeEnum,
    NumberFormatEnum,
    SortOrderEnum,
    LegendPositionEnum,
    ColorPaletteEnum,
} from './sharedResolversTypes';

export const GraphType = new GraphQLObjectType({
    name: 'Graph',
    fields: () => ({
        id: { type: new GraphQLNonNull(GraphQLID) },
        organizationId: { type: GraphQLID },
        name: { type: new GraphQLNonNull(GraphQLString) },
        viewName: { type: new GraphQLNonNull(GraphQLString) },
        chartType: { type: new GraphQLNonNull(ChartTypeEnum) },
        chartTitle: { type: new GraphQLNonNull(GraphQLString) },
        measures: { type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(GraphQLString))) },
        dimensions: { type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(GraphQLString))) },
        dates: { type: new GraphQLNonNull(new GraphQLList(new GraphQLNonNull(GraphQLString))) },
        filters: { type: new GraphQLNonNull(GraphQLJSON) },
        orderByField: { type: new GraphQLNonNull(GraphQLString) },
        orderByDirection: { type: new GraphQLNonNull(SortOrderEnum) },
        numberFormat: { type: new GraphQLNonNull(NumberFormatEnum) },
        numberPrecision: { type: new GraphQLNonNull(GraphQLInt) },
        colorPalette: { type: new GraphQLNonNull(ColorPaletteEnum) },
        primaryColor: { type: new GraphQLNonNull(GraphQLString) },
        sortOrder: { type: new GraphQLNonNull(SortOrderEnum) },
        legendPosition: { type: new GraphQLNonNull(LegendPositionEnum) },
        kpiValue: { type: GraphQLFloat },
        kpiLabel: { type: GraphQLString },
        kpiSecondaryValue: { type: GraphQLFloat },
        kpiSecondaryLabel: { type: GraphQLString },
        kpiShowTrend: { type: new GraphQLNonNull(GraphQLBoolean) },
        kpiTrendPercentage: { type: GraphQLFloat },
        showXAxisGridLines: { type: new GraphQLNonNull(GraphQLBoolean) },
        showYAxisGridLines: { type: new GraphQLNonNull(GraphQLBoolean) },
        showGridLines: { type: new GraphQLNonNull(GraphQLBoolean) },
        showRegressionLine: { type: new GraphQLNonNull(GraphQLBoolean) },
        xAxisLabel: { type: GraphQLString },
        yAxisLabel: { type: GraphQLString },
        maxDataPoints: { type: new GraphQLNonNull(GraphQLInt) },
        primaryDimension: { type: new GraphQLNonNull(GraphQLString) },
        secondaryDimension: { type: GraphQLString },
        selectedMeasure: { type: new GraphQLNonNull(GraphQLString) },
        createdAt: { type: new GraphQLNonNull(GraphQLString) },
        updatedAt: { type: new GraphQLNonNull(GraphQLString) },
    }),
});

export const GraphInput = new GraphQLInputObjectType({
    name: 'GraphInput',
    fields: {
        name: { type: new GraphQLNonNull(GraphQLString) },
        viewName: { type: new GraphQLNonNull(GraphQLString) },
        chartType: { type: new GraphQLNonNull(ChartTypeEnum) },
        chartTitle: { type: new GraphQLNonNull(GraphQLString) },
        measures: { type: new GraphQLList(GraphQLString) },
        dimensions: { type: new GraphQLList(GraphQLString) },
        dates: { type: new GraphQLList(GraphQLString) },
        filters: { type: GraphQLJSON },
        orderByField: { type: GraphQLString },
        orderByDirection: { type: SortOrderEnum },
        numberFormat: { type: NumberFormatEnum },
        numberPrecision: { type: GraphQLInt },
        colorPalette: { type: ColorPaletteEnum },
        primaryColor: { type: GraphQLString },
        sortOrder: { type: SortOrderEnum },
        legendPosition: { type: LegendPositionEnum },
        kpiValue: { type: GraphQLFloat },
        kpiLabel: { type: GraphQLString },
        kpiSecondaryValue: { type: GraphQLFloat },
        kpiSecondaryLabel: { type: GraphQLString },
        kpiShowTrend: { type: GraphQLBoolean },
        kpiTrendPercentage: { type: GraphQLFloat },
        showXAxisGridLines: { type: GraphQLBoolean },
        showYAxisGridLines: { type: GraphQLBoolean },
        showGridLines: { type: GraphQLBoolean },
        showRegressionLine: { type: GraphQLBoolean },
        xAxisLabel: { type: GraphQLString },
        yAxisLabel: { type: GraphQLString },
        maxDataPoints: { type: GraphQLInt },
        primaryDimension: { type: GraphQLString },
        secondaryDimension: { type: GraphQLString },
        selectedMeasure: { type: GraphQLString },
    },
});
