import type { GraphRow, Graph } from './types';

/** Convert a graph database row to camelCase for GraphQL */
export const graphRowToCamelCase = (row: GraphRow): Graph => ({
    id: row.id,
    organizationId: row.organization_id,
    name: row.name,
    viewName: row.view_name,
    chartType: row.chart_type,
    chartTitle: row.chart_title,
    measures: row.measures,
    dimensions: row.dimensions,
    dates: row.dates,
    filters: row.filters,
    orderByField: row.order_by_field,
    orderByDirection: row.order_by_direction,
    numberFormat: row.number_format,
    numberPrecision: row.number_precision,
    colorPalette: row.color_palette,
    primaryColor: row.primary_color,
    sortOrder: row.sort_order,
    legendPosition: row.legend_position,
    kpiValue: row.kpi_value ? parseFloat(row.kpi_value) : null,
    kpiLabel: row.kpi_label,
    kpiSecondaryValue: row.kpi_secondary_value ? parseFloat(row.kpi_secondary_value) : null,
    kpiSecondaryLabel: row.kpi_secondary_label,
    kpiShowTrend: row.kpi_show_trend,
    kpiTrendPercentage: row.kpi_trend_percentage ? parseFloat(row.kpi_trend_percentage) : null,
    showXAxisGridLines: row.show_x_axis_grid_lines,
    showYAxisGridLines: row.show_y_axis_grid_lines,
    showGridLines: row.show_grid_lines,
    showRegressionLine: row.show_regression_line,
    xAxisLabel: row.x_axis_label,
    yAxisLabel: row.y_axis_label,
    maxDataPoints: row.max_data_points,
    primaryDimension: row.primary_dimension,
    secondaryDimension: row.secondary_dimension,
    selectedMeasure: row.selected_measure,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
});
